version: '2'
services:
  db:
    image: mysql:5.7.32
    volumes:
      - ./docker/db/database.sql:/docker-entrypoint-initdb.d/database.sql
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=anywize2021
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=anywize2021
      - UPLOAD_LIMIT=3000000000
    restart: always
    ports:
      - 8181:80
    volumes:
      - /sessions
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
volumes:
  mysql-data:
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
